/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectakhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan Aditama
 */
public class login extends javax.swing.JFrame {

    Connection conn;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        conn = koneksi.getConnection();
    }

//    private void login(){
//        try{
//          String sql = "SELECT * FROM login WHERE email = ? AND password = ?";
//          PreparedStatement ps = conn.prepareStatement(sql);
//          ps.setString(1, txtEmail.getText());
//          ps.setString(2, txtPw.getText());
//          ps.executeQuery();
//          JOptionPane.showMessageDialog(this, "Anda berhasil login");
//          kota kota = new kota();
//          kota.setVisible(true);
//          dispose();
//        }catch (SQLException e){
//            System.out.println("Error Save Data" + e.getMessage());
//        }
//    }
    private int validateLogin(String username, String password){
        String sql = "SELECT id_user FROM login WHERE email = ? AND password = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, username);
                ps.setString(2, password); // Anda bisa mengenkripsi password menggunakan hash di sini
                ResultSet rs = ps.executeQuery();

            if (rs.next()){
                return rs.getInt("id_user");
            }// Login berhasil
            // Login gagal
            } catch (SQLException e) {
                e.getMessage();
        }
            return -1;
    }
    private int validateLoginAdmin(String username, String password){
        String sql = "SELECT id_admin FROM admin WHERE email_admin = ? AND password_admin = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, username);
                ps.setString(2, password); // Anda bisa mengenkripsi password menggunakan hash di sini
                ResultSet rs = ps.executeQuery();

            if(rs.next()){
                return rs.getInt("id_admin");
            }// Login berhasil
            // Login gagal
            } catch (SQLException e) {
                System.out.println("Error Save Data" + e.getMessage());
        }
            return -1;
    }
    
    private void saveDataRegist(){
        if(txtNama.getText().isEmpty()|| txtPw.getText().isEmpty()||txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Salah satu form masih kosong", "peringatan", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
            String sql = "INSERT INTO login (nama_user, email, password) VALUES (?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txtNama.getText());
            ps.setString(2, txtEmail.getText());
            ps.setString(3, txtPw.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data saved successfully");
          } catch (SQLException e) {
            System.out.println("Error Save Data" + e.getMessage());
          }
        }
    }
    
    public class Session {
        private static int userId;

        public static void setUserId(int id) {
            userId = id;
        }

        public static int getUserId() {
            return userId;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        regis = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPw = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        loginAdmin = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPassAdmin = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        login.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        login.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel4.setText("Belum Punya Akun?");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("LOGIN SEBAGAI ADMIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        login.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("REGISTRASI");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        login.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jPanel1.add(login, "card2");

        regis.setBackground(new java.awt.Color(255, 255, 255));
        regis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Nama");
        regis.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("REGRISTRASI");
        regis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        regis.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));
        regis.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));
        regis.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        regis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));
        regis.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 130, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        regis.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel5.setText("Sudah punya akun?");
        regis.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("LOGIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        regis.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jPanel1.add(regis, "card3");

        loginAdmin.setBackground(new java.awt.Color(255, 255, 255));
        loginAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("LOGIN KHUSUS ADMIN");
        loginAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setText("Email");
        loginAdmin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        loginAdmin.add(txtAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setText("Password");
        loginAdmin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtPassAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassAdminActionPerformed(evt);
            }
        });
        loginAdmin.add(txtPassAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 130, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        loginAdmin.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("LOGIN SEBAGAI USER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        loginAdmin.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jPanel1.add(loginAdmin, "card4");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = txtUser.getText();
        String password = txtPass.getText(); // Mengambil password
        int idUser = validateLogin(username, password);
        if (idUser != -1) {
            JOptionPane.showMessageDialog(this, "Login Berhasil!" + idUser);
            // Jika login berhasil, buka form utama aplikasi atau pindah ke frame lain
            // Misalnya, new MainForm().setVisible(true);
            Session.setUserId(idUser);
            new kotaa().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password salah.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginAdmin.setVisible(true);
        login.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        saveDataRegist();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        regis.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPassAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassAdminActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String username = txtAdmin.getText();
        String password = txtPassAdmin.getText(); // Mengambil password
        int idAdmin = validateLoginAdmin(username, password);
        admin admin = new admin();
        
        if (idAdmin != -1) {
            JOptionPane.showMessageDialog(this, "Login Berhasil!" + idAdmin);
            // Jika login berhasil, buka form utama aplikasi atau pindah ke frame lain
            // Misalnya, new MainForm().setVisible(true);
            Session.setUserId(idAdmin);
            admin.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password salah.");
        }
        
        
        DefaultTableModel model = new DefaultTableModel();
        admin.tblMakanan.setModel(model);

        model.addColumn("Id_makanan");
        model.addColumn("Nama_makanan");
        model.addColumn("Deskripsi");
        model.addColumn("Gambar");
        model.addColumn("Rating");
        
        model.setRowCount(0);

        try {
            String sql = "SELECT id_makanan, nama_makanan, deskripsi, gambar, rating FROM makanan";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
               // Menambahkan baris ke dalam model tabel
                int id = rs.getInt("id_makanan");
                String nama = rs.getString("nama_makanan");
                String deskripsi = rs.getString("deskripsi");
                byte[] gambarBytes = rs.getBytes("gambar");
                int rating = rs.getInt("rating");

//                Konversi byte[] ke ImageIcon;
                ImageIcon gambar = null;
                if (gambarBytes != null) {
                    gambar = new ImageIcon(gambarBytes);
                }

                // Tambahkan data ke tabel
                model.addRow(new Object[]{id, nama, deskripsi,gambar, rating});
            }
        } catch (SQLException e) {
           System.out.println("Error Save Data" + e.getMessage());
         }
        
        DefaultTableModel modelU = new DefaultTableModel();
        admin.tblUser.setModel(modelU);

        modelU.addColumn("Id_user");
        modelU.addColumn("Nama_user");
        modelU.addColumn("Email");
        modelU.addColumn("Password");
        
        modelU.setRowCount(0);

        try {
            String sql = "SELECT * FROM login";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
               // Menambahkan baris ke dalam model tabel
               modelU.addRow(new Object[]{
               rs.getInt("id_user"),
               rs.getString("nama_user"),
               rs.getString("email"),
               rs.getString("password")
             });
            }
        } catch (SQLException e) {
           System.out.println("Error Save Data" + e.getMessage());
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        loginAdmin.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        regis.setVisible(true);
        login.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel login;
    private javax.swing.JPanel loginAdmin;
    private javax.swing.JPanel regis;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassAdmin;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
